# Pandas
WOrk with Tabular Data i.e. **Data Sets**  
seaborn also used Pandas **DataFrame** Behind the Scenes

In [2]:
import pandas as pd
import numpy as np

## DataFrames
We can directly Create DataFrames out of dicts

In [12]:
userData = {
    "SubA" :np.random.randint(0,101,10),
    "SubB" :np.random.randint(0,101,10),
    "SubC" :np.random.randint(0,101,10),
    "SubD" :np.random.randint(0,101,10),
    "SubE" :np.random.randint(0,101,10)
}

In [23]:
# userDF = pd.DataFrame(userData,dtype = "float32")
userDF = pd.DataFrame(userData)
userData

{'SubA': array([ 43, 100,  34,  17,  69,   4,  45,  21,  85,  68]),
 'SubB': array([26, 87, 23, 94, 94, 13,  6, 85, 21, 57]),
 'SubC': array([54, 33, 71, 71, 61,  5, 13, 66,  8, 93]),
 'SubD': array([57, 16, 73, 30, 68, 28, 21, 35, 71, 85]),
 'SubE': array([49, 59, 19, 31, 87, 12, 27, 27, 68, 69])}

In [16]:
userDF.head()

SubA  SubB  SubC  SubD  SubE
0    43    26    54    57    49
1   100    87    33    16    59
2    34    23    71    73    19
3    17    94    71    30    31
4    69    94    61    68    87

In [22]:
print(userDF.columns)

Index(['SubA', 'SubB', 'SubC', 'SubD', 'SubE'], dtype='object')


In [27]:
userDF.to_csv('marks.csv')

In [4]:
myData = pd.read_csv('marks.csv')
print(myData)


   Unnamed: 0  SubA  SubB  SubC  SubD  SubE
0           0    43    26    54    57    49
1           1   100    87    33    16    59
2           2    34    23    71    73    19
3           3    17    94    71    30    31
4           4    69    94    61    68    87
5           5     4    13     5    28    12
6           6    45     6    13    21    27
7           7    21    85    66    35    27
8           8    85    21     8    71    68
9           9    68    57    93    85    69


In [5]:
myData=myData.drop(columns=['Unnamed: 0'])
print(myData)

   SubA  SubB  SubC  SubD  SubE
0    43    26    54    57    49
1   100    87    33    16    59
2    34    23    71    73    19
3    17    94    71    30    31
4    69    94    61    68    87
5     4    13     5    28    12
6    45     6    13    21    27
7    21    85    66    35    27
8    85    21     8    71    68
9    68    57    93    85    69


## Pandas Basics - 2 

In [6]:
myData.describe()

SubA       SubB       SubC       SubD       SubE
count   10.000000  10.000000  10.000000  10.000000  10.000000
mean    48.600000  50.600000  47.500000  48.400000  44.800000
std     31.209685  36.457586  30.747177  25.051946  25.143146
min      4.000000   6.000000   5.000000  16.000000  12.000000
25%     24.250000  21.500000  18.000000  28.500000  27.000000
50%     44.000000  41.500000  57.500000  46.000000  40.000000
75%     68.750000  86.500000  69.750000  70.250000  65.750000
max    100.000000  94.000000  93.000000  85.000000  87.000000

In [8]:
myData.tail(n=3)

   SubA  SubB  SubC  SubD  SubE
7    21    85    66    35    27
8    85    21     8    71    68
9    68    57    93    85    69


In [13]:
# Accessing PArticular Row by its index
myData.iloc[8]

SubA    85
SubB    21
SubC     8
SubD    71
SubE    68
Name: 8, dtype: int64

In [15]:
# Accessing particular row and Cell
myData.iloc[8,0] # myData.iloc[8][0]

85

In [19]:
# Get index of an specific column
idx = myData.columns.get_loc('SubC')
idx

2

In [24]:
myData.iloc[3,idx]

71

In [27]:
# Printing multiple cols 
# making a list of col indices
idx = [myData.columns.get_loc('SubC'),myData.columns.get_loc('SubB')]
myData.iloc[3,idx]

SubC    71
SubB    94
Name: 3, dtype: int64

In [36]:
# Slicing
myData.iloc[:,3]

0    57
1    16
2    73
3    30
4    68
5    28
6    21
7    35
8    71
9    85
Name: SubD, dtype: int64

### Sorting by specific values

In [43]:
# By Default Ascending for descending ascending = False

# by : Priority List


myData.sort_values(by=['SubC','SubD'],ascending = True)

SubA  SubB  SubC  SubD  SubE
5     4    13     5    28    12
8    85    21     8    71    68
6    45     6    13    21    27
1   100    87    33    16    59
0    43    26    54    57    49
4    69    94    61    68    87
7    21    85    66    35    27
3    17    94    71    30    31
2    34    23    71    73    19
9    68    57    93    85    69

In [48]:
# To Numpy Array
dataArray  = myData.values
print(dataArray)

[[ 43  26  54  57  49]
 [100  87  33  16  59]
 [ 34  23  71  73  19]
 [ 17  94  71  30  31]
 [ 69  94  61  68  87]
 [  4  13   5  28  12]
 [ 45   6  13  21  27]
 [ 21  85  66  35  27]
 [ 85  21   8  71  68]
 [ 68  57  93  85  69]]


In [47]:
print(type(myData))
print(myData.shape)

<class 'pandas.core.frame.DataFrame'>
(10, 5)


### Numpy Array's to DataFrame

In [49]:
df = pd.DataFrame(dataArray,columns = ['Physics','Chem','Maths','CS','English'])

In [50]:
df

Physics  Chem  Maths  CS  English
0       43    26     54  57       49
1      100    87     33  16       59
2       34    23     71  73       19
3       17    94     71  30       31
4       69    94     61  68       87
5        4    13      5  28       12
6       45     6     13  21       27
7       21    85     66  35       27
8       85    21      8  71       68
9       68    57     93  85       69

In [51]:
df.to_csv('pcm.csv')

In [53]:
# To avpid storing indices
df.to_csv( 'newPCM.csv',index = False)