# Numpy 
MAthematical Operations

In [2]:
import numpy as np


In [15]:
a = np.array([1,2,3,4,5])
print(a)

print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [16]:
# [ [first_row] ,  [second_row]....   ]
b = np.array([[1],[2],[3]])
print(b[0][0])
print(b[1][0])


1
2


Numpy Treats 2-D array of columns =1 and 1-D array as different  
It can be experienced by using .shape and all.

In [17]:
print(a.shape)
print(b.shape)

(5,)
(3, 1)


### Create Array of Zeros, Ones aka Custom Arrays

In [26]:
a = np.zeros((3,))
# same as
# .zeros(3)
# .zeros((3))
print(a)

[0. 0. 0.]


In [30]:
# 2-D Arrays
a = np.zeros((3,1))
# similarly np.ones()
print(a)

[[0.]
 [0.]
 [0.]]


#### np.full()
creating array of constants

In [33]:
a = np.full((2,3),-1)
print(a)

[[-1 -1 -1]
 [-1 -1 -1]]


In [36]:
# Identity Matrix
# square matrix hence one dimension only
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [59]:
# Random Matrix
rm = np.random.random((3,3))
print(rm)

[[0.13670836 0.78565695 0.72567364]
 [0.36141758 0.54741444 0.52027649]
 [0.88166319 0.90894079 0.52478747]]


## Slicing 

In [72]:
# accessing 2nd column
# Personal Experience 
# While Taking a Range :,1 [][] doesnt work
# So use[:,1]

# [][] this always takes given values for first(row) values


print(rm[:,1])

[0.78565695 0.54741444 0.90894079]


In [73]:
# Updating Values
rm[1,1] = 0
print(rm)

[[0.13670836 0.78565695 0.72567364]
 [0.36141758 0.         0.52027649]
 [0.88166319 0.90894079 0.52478747]]


In [75]:
# Updating Values :Range
rm[2,0:] = -1
print(rm)

[[ 0.13670836  0.78565695  0.72567364]
 [ 0.36141758  0.          0.52027649]
 [-1.         -1.         -1.        ]]


## Data Types

In [76]:
print(rm.dtype)

float64


In [85]:
# Creating IntType Array
# dtype = np.int64
a = np.ones((3,3),dtype = np.int64)
print(a)
print(a.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int64


## Mathematical Operations


In [107]:
a = np.array([[1,1],[1,1]])
b = np.array([[2,2],[2,2]],dtype = np.int64)

In [108]:
print(a)
print(b)

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


In [109]:
#Addition 
print(a+b)
print(np.add(a,b))

[[3 3]
 [3 3]]
[[3 3]
 [3 3]]


In [90]:
#Subtraction 
print(a-b)
#print(np.add(a,-b))
print(np.subtract(a,b))

[[-1 -1]
 [-1 -1]]
[[-1 -1]
 [-1 -1]]


In [94]:
# multiplication
# ELEMENT WISE
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))

[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


### Note
All the Above Operations are Element wise

In [103]:
# Square Root
print(np.sqrt(b))
print(b.dtype)

[[1.18920712 1.18920712]
 [1.18920712 1.18920712]]
float64


In [112]:
# Matrix Multiplication/ Dot Product'
print(a)
print(b)

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


In [113]:
print(a.dot(b))
print(np.dot(a,b))

[[4 4]
 [4 4]]
[[4 4]
 [4 4]]


In [117]:
# Multiplication(Dot Product) of Vectors : Scaler

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

#Scaler
print(a.dot(b))

30


## Vectors


In [119]:
a = np.array([1,2,3,4])
print(sum(a))
print(np.sum(a))

10
10


In [120]:
a = np.array([[1,2],[3,4]])
# sum of all elements of the matrix
print(np.sum(a))

[4 6]
10


In [123]:
# Column wise sum
print(np.sum(a,axis=0))

# Row wise sum : axis = 1
print(np.sum(a,axis=1))

[4 6]
[3 7]


In [139]:
# Stack Function
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [140]:
print(b**2)
b = b**2

[ 1  4  9 16]


In [131]:
# Stacking of Arrays

# array = row : axis = 0 also DEFAULT
np.stack((a,b),axis = 0)

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [132]:
# array = columns : axis = 0 also DEFAULT
np.stack((a,b),axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

### Reshape 

In [141]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

a = np.stack((a,b),axis = 0)
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [155]:
#Reshaping an np Array

# Reshapes in ROW Major Order
# number of elements must remain same

print( a.reshape((2,4)))
print( a.reshape((4,2)))

# you can leave one dimension as -1 and it will figure out
print( a.reshape((-1,8)))

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
[[ 1  2  3  4  1  4  9 16]]
